development:
  adapter: postgresql
  database: podcastilator_dev
  host: localhost
  pool: 5
  timeout: 5000
  password:

test:
  adapter: postgresql
  database: podcastilator_test
  host: localhost
  pool: 5
  timeout: 5000
  password:
