# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f580bf2dc15700df90dc59ce73fb8fa8acdf431aaa2444cc94901db93ea5da5f8beafd130d5a6f34ae527ffd82edee6523804e70daf0635687dbb741b124bcc

test:
  secret_key_base: ffcc1d68db497b2b9d267167bcaab1adf83a71d5a94ee76cb32599fcf82ae9acf74e3c37f9a5e31ddb037f5aa55f53256022b0ef6979fc443d5f09a200a3a664

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
